name: Generate PHP Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'plugins/graphic_data_plugin/**/*.php'
      - '.github/workflows/generate-docs.yml'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP with phpDocumentor
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpdoc

      - name: Create documentation directory
        run: mkdir -p ./docs/function_documentation

      # 👇 Debug step to verify plugin directory tree
      - name: Debug directory tree
        run: |
          echo "Listing plugin directory structure (depth 3):"
          find ./plugins/graphic_data_plugin -maxdepth 3 -type d | sort

      - name: Generate documentation with phpDocumentor
        run: phpdoc run --config=./plugins/graphic_data_plugin/phpdoc.xml

      - name: Commit documentation changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Update documentation [skip ci]" && git push)
